services:
  # The Database
  db:
    image: postgres:15-alpine
    container_name: expense_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=helloPOSTGRES2005
      - POSTGRES_DB=ExpenseTracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Cache (for JWT blacklisting/Rate limiting)
  redis:
    image: redis:alpine
    container_name: expense_redis
    ports:
      - "6379:6379"

  # The FastAPI App
  api:
    build: .
    container_name: expense_api
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=helloPOSTGRES2005
      - DATABASE_NAME=ExpenseTracker
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=your_super_secret_jwt_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
