services:
  # The Database
  db:
    image: postgres:15-alpine
    container_name: expense_db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Cache (for JWT blacklisting/Rate limiting)
  redis:
    image: redis:7-alpine
    container_name: expense_redis
    restart: always
    ports:
      - "${REDIS_HOST_PORT}:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]

  # The FastAPI App
  api:
    build: .
    container_name: expense_api
    ports:
      - "${API_HOST_PORT:-9000}:9000"
    volumes:
      - .:/app
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REDIS_URL=${REDIS_URL}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
      - IS_PRODUCTION=${IS_PRODUCTION}
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
